name: 'ScratchLink Version Action'
description: 'Update ScratchLink Versions On Build'
inputs:
  token:  # id of input
    description: 'github token'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'