name: 'ScratchLink Version Action'
description: 'Update ScratchLink Versions On Build'
inputs:
  repo:  # id of input
    description: 'editConfig or scratchlinkcodes'
    required: true
    default: 'editConfig'
runs:
  using: 'node16'
  main: 'dist/index.js'